# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dir_data": "models.ipynb",
         "dir_imgs": "models.ipynb",
         "dir_colr": "models.ipynb",
         "dir_gray": "models.ipynb",
         "denorm": "data.ipynb",
         "torch2np": "data.ipynb",
         "rgb2gray": "data.ipynb",
         "get_src": "data.ipynb",
         "get_data": "data.ipynb",
         "img2tensor": "models.ipynb",
         "leaf_modules": "models.ipynb",
         "gram_matrix": "models.ipynb",
         "FeatureLoss": "models.ipynb",
         "DisplayResultsCallback": "models.ipynb"}

modules = ["data.py",
           "models.py"]

doc_url = "https://fastai.github.io/deoldify/"

git_url = "https://github.com/fastai/deoldify/tree/master/"

def custom_doc_links(name): return None
